"""added UserStats table

Revision ID: 01b7792b985d
Revises: edc54850f183
Create Date: 2025-02-22 22:44:25.364017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b7792b985d'
down_revision = 'edc54850f183'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('master_count', sa.Integer(), nullable=False),
    sa.Column('slave_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Создаем записи в user_stats для существующих пользователей
    connection = op.get_bind()
    connection.execute(
        sa.text("""
            INSERT INTO user_stats (id, rating, master_count, slave_count)
            SELECT id, 0, 0, 0
            FROM users
        """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stats')
    # ### end Alembic commands ###
