"""added next daily field

Revision ID: 5be6654ac2e7
Revises: 5d9131e50dc0
Create Date: 2025-02-22 19:22:33.269032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be6654ac2e7'
down_revision = '5d9131e50dc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('next_daily_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'next_daily_time')
    # ### end Alembic commands ###
