"""Add is_active field

Revision ID: 5d9131e50dc0
Revises: 591c2f0eab58
Create Date: 2025-02-22 18:15:33.542048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9131e50dc0'
down_revision = '591c2f0eab58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Добавляем колонку, разрешая NULL
    op.add_column('chats', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # 2. Устанавливаем значение TRUE для всех существующих записей
    op.execute("UPDATE chats SET is_active = TRUE")
    op.execute("UPDATE users SET is_active = TRUE")
    
    # 3. Меняем колонку на NOT NULL
    op.alter_column('chats', 'is_active',
                    existing_type=sa.Boolean(),
                    nullable=False)
    op.alter_column('users', 'is_active',
                    existing_type=sa.Boolean(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('chats', 'is_active')
    # ### end Alembic commands ###
