"""added last_picture_date and chat name

Revision ID: 8b2d3b81c101
Revises: d9d83d418069
Create Date: 2025-02-26 23:12:02.494573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2d3b81c101'
down_revision = 'd9d83d418069'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('user_stats', sa.Column('launched_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'launched_count')
    op.drop_column('chats', 'name')
    # ### end Alembic commands ###
