"""added last_picture_date

Revision ID: d9d83d418069
Revises: 01b7792b985d
Create Date: 2025-02-24 20:00:30.861604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d83d418069'
down_revision = '01b7792b985d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('last_picture_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'last_picture_date')
    # ### end Alembic commands ###
